### ISSUE TITLE
Announce Summer of Haskell on this website instead of Reddit

### ISSUE THREAD

**Issue by wisn** [haskell-org/summer-of-haskell#1]
Why the update about Summer of Haskell is announced on Reddit instead of this website? In Indonesia, Reddit is blocked by the government. So, it's would be really helpful if all about Summer of Haskell informations are stored here. Thanks!

**Comment by jaspervdj** [comment]
Hey @wisn,

We posted about the update on Summer of Haskell on Reddit  -- but Reddit by no means the "official" or only channel.  We indeed plan to store all information on this website but we will also continue to send out updates on Reddit, Twitter (<https://twitter.com/haskellorg>) and of course the Haskell-Cafe mailing list (<https://mail.haskell.org/mailman/listinfo/haskell-cafe>).

**Comment by wisn** [comment]
I see...
I do love to help to update this website. So, any information will be available as soon as possible. Let me know if it's something to do.

**Comment by jaspervdj** [comment]
Hey @wisn, after giving this some thought I've added a `/news.html` page to this website which mirrors the announcements.  That should solve the problem.  :-)

**Comment by wisn** [comment]
Thanks, @jaspervdj!
