### ISSUE TITLE
Plan for GSoC 2018

### ISSUE THREAD

**Issue by wisn** [haskell-org/summer-of-haskell#10]
The GSoC 2018 has been [announced](https://opensource.googleblog.com/2017/09/announcing-google-summer-of-code-2018.html). I hope that Haskell gets fund by Google again. Is there something we, as a part of Haskell community, can do to help?

**Comment by jaspervdj** [comment]
The most important thing will be to update the projects page and solicit project maintainers to add new projects.

**Comment by jaspervdj** [comment]
@wisn Let me know if you're interested in helping me fine-tune project ideas and poking project maintainers.  My email is on my github profile.

**Comment by wisn** [comment]
@jaspervdj I'm in!
