### ISSUE TITLE
Tentative proposal: take up the ImprovedLLVMBackend ticket

### ISSUE THREAD

**Issue by jberryman** [haskell-org/summer-of-haskell#100]
https://ghc.haskell.org/trac/ghc/wiki/ImprovedLLVMBackend
https://ghc.haskell.org/trac/ghc/ticket/10074

I'm not really sure where the plan stands based on that ticket. Maybe just someone giving some love and attention to the optimizer passes would be a good project.

**Comment by jaspervdj** [comment]
@jberryman Do you have any mentors in mind?  I'm happy to write up some proposal.

**Comment by jberryman** [comment]
No, and sorry I'm not a student myself, I just had the thought this might be a good general focus for GSoC (sorry if this isn't constructive).

**Comment by jaspervdj** [comment]
No worries, I'll ask around!

**Comment by angerman** [comment]
Looks like I tried to and then failed to actually write my comment here.  I'd rather see us pouring some resources into the bitcode generating llvm-ng backend, instead of int the textual ir backend. I'd be happy to mentor such a project if a sufficiently strong candidate applies.

**Comment by jaspervdj** [comment]
Closing this to clean up for GSoC 2020.
