### ISSUE TITLE
Project Idea: Stack

### ISSUE THREAD

**Issue by decentral1se** [haskell-org/summer-of-haskell#11]
Hi folks, I was just reading the [Final results for 2017](https://summer.haskell.org/news/2017-09-15-final-results.html) post and saw you're looking for project ideas. I've lately been fishing around for funding to allow people to hack on Stack, for example [the MOSS programme](https://groups.google.com/forum/#!topic/mozilla.moss/w6xf5O6bRG8) - I'd love to get Stack in as a GSoC project! I believe we can put together a solid proposal given that Stack is quite an important tool in the community and there is a lot of important work to be done that when implemented is delivered directly to users - hence, a lot of impact for students! Also, a small group of contributors has been growing around core devs in the last months, so there would be good support for anyone getting on board. If this is a goer, please let me know how I can advance this along and what kind of a proposal that needs to put together!

**Comment by jaspervdj** [comment]
Yes, I would also love to have a Stack/Stackage project this year.  What we really need is a concrete idea or project for someone to work on, I'm not familiar enough with Stack to propose something like that though.  A stupid example of a concrete idea would be e.g. "add native support for producing `.deb` installers to stack".

Coincidentally, I was planning on sending out a "call for project ideas" out today so thanks for kicking this off :-)

**Comment by decentral1se** [comment]
Great! @jaspervdj, is there some place that lists properties of what a good project might be? I suppose so but my search-foo is failing me right now. Glad to see this taking off anyway, I'll let other Stack(age) people know about this and see what comes of it.

**Comment by jaspervdj** [comment]
@lwm My current definition is:

> Projects should benefit as many people as possible -- e.g. an improvement to GHC will benefit more people than an update to a specific library or tool, but both are definitely valid.  New libraries and applications written in Haskell, rather than improvements to existing ones, are also accepted.  Project ideas should be concrete and small enough in scope such that they can be finished by a student in three months.

You can find some inspiration in last year's ideas: <https://summer.haskell.org/ideas.html>.

**Comment by decentral1se** [comment]
Thanks! Seems like nothing is cooking so far. Closing.

**Comment by jaspervdj** [comment]
@lwm Are you sure about that?  Cabal/Hackage is probably getting a student so it feels like stack should also have a shot.  Anyway there's still a lot of time, I'll check back with you back closer to the student application period.
