### ISSUE TITLE
Dear ImGui bindings

### ISSUE THREAD

**Issue by ethercrow** [haskell-org/summer-of-haskell#112]
> Dear ImGui: Bloat-free Immediate Mode Graphical User interface for C++ with minimal dependencies

Repository: https://github.com/ocornut/imgui

Dear ImGui is a mature and widely used open source library with corporate backing by Google, Blizzard, Ubisoft and others.

Many languages (but notably not Haskell) have bindings to Dear ImGui via its C API and machine-readable description of said API available here: https://github.com/cimgui/cimgui

![simple_enterprise_application](https://raw.githubusercontent.com/wiki/ocornut/imgui/web/v175/capture_readme_styles_0001.png)

Today if someone wants a simple GUI application with a few buttons, a textfield and a progressbar for some experiments or for some other niche purpose, the choice is basically:

- Take a relatively minimal library like SDL or Gloss and suffer having to do widgets and layout yourself
- Take some relatively heavyweight library with widgets and layouts like GTK, WxWidgets or FLTK and suffer having to compile them to all target platforms you need

Having Dear ImGui would provide a third (and hopefully best for some cases) option here.

I personally don't have any experience with Dear ImGui, so I would not be able to mentor this, just hope someone is able and willing.

**Comment by jaspervdj** [comment]
This sounds reasonable but would need a mentor with Dear ImGui and FFI/bindings experience.

**Comment by ethercrow** [comment]
@ekmett @ocharles @osa1 @glguy maybe you know someone interested in mentoring this?

**Comment by dpwiz** [comment]
There's one library listed in on ImGui wiki: https://github.com/dbousamra/imgui-haskell

It's incomplete and ripe for takeover.

**Comment by wujilingfeng** [comment]
You can watch  this website https://github.com/haskell-game/dear-imgui.hs.
I haven't try this , you can tell us how about this library if you test it.

**Comment by wujilingfeng** [comment]
https://github.com/haskell-game/dear-imgui.hs

**Comment by ethercrow** [comment]
@ocharles @sheaf maybe you have GSoC-able ideas for the project?

**Comment by ekmett** [comment]
I'm quite familiar with ImGui internals. If a body is still needed to help, let me know.

**Comment by ocharles** [comment]
I'd be happy to mentor, there's plenty left to do on the haskell-game library I'm helping build

**Comment by jaspervdj** [comment]
Awesome, sounds like there's more than enough support!  All we need for now is a small description to give the students some direction for their ideas.  Is anyone able to put this up in a PR?

**Comment by dpwiz** [comment]
BTW, https://github.com/haskell-game/dear-imgui.hs is a thing now. It is even on [Hackage](https://hackage.haskell.org/package/dear-imgui).

**Comment by jaspervdj** [comment]
Cleaning up for 2023, if you receive this notification and have ideas for this year, please submit them!
