### ISSUE TITLE
Advice for GSOC 2020

### ISSUE THREAD

**Issue by KushajveerSingh** [haskell-org/summer-of-haskell#125]
I want to contribute to haskell as part of GSOC 2020. I have gone through the proposed ideas list. I have experience with PyTorch and fastai. So I was wondering what would be the best way for me to contribute to this project. 

All my relevant experience is summarized on my website [https://kushajveersingh.github.io/ ](https://kushajveersingh.github.io/).

**Comment by jaspervdj** [comment]
Hey @KushajveerSingh, please reach out to the relevant mentors directly or use the [general contact page](https://summer.haskell.org/contact.html).
