### ISSUE TITLE
Project idea: Machine learning for compiler options

### ISSUE THREAD

**Issue by chshersh** [haskell-org/summer-of-haskell#13]
The idea described briefly in this PDF:

* http://opensky.ucar.edu/islandora/object/siparcs%3A66/datastream/PDF/view

Projects with similar ideas are already in development for years for C++ compilers. In short: GHC has a lot of optimization options according to [user gudie](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-optimisation.html) including strange options like `-fmax-inline-memcpy-insns=⟨n⟩`. Probably, not using default values of these options may increase performance of your program/library. But obviously you don't want to manually figure out the perfect set of options.

The idea is to use some machine learning and parameter optimizations technique (not advanced for now) to figure out better compiler flags for your program. The perfect (and probably unrealistic) result is to have tool which you can call once in your project root and the output of this too is set of compiler flags which gives you better performance than default one. 

As I see it now: you need to implement benchmarks and this tool will parse result of benchmarks, choose GHC options, recompile project with new set of options, run benchmarks again and so on.

**Comment by jaspervdj** [comment]
I could be mistaken but I don't think GHC has _that many_ options available.  It might make sense when using `-fvia-C` and then the plethora of `C`-related flags.  Would you be willing to look into approximately how many combinations of flags there are when looking only at the Haskell ones?

**Comment by chshersh** [comment]
@jaspervdj Thanks for your feedback on my issue!

This tool can be used to check how good experimental flags are, like this one:

```
-fdicts-cheap
    A very experimental flag that makes dictionary-valued expressions seem cheap to the optimiser.
```

The problem is not so much about number of flags. The problem is in the fact that some flags take integer parameters. Like these ones:

```
-fliberate-case-threshold=⟨n⟩      (Default: 2000)
-fmax-inline-alloc-size=⟨n⟩        (Default: 128)
-fmax-inline-memcpy-insns=⟨n⟩      (Default: 32)
-fmax-inline-memset-insns=⟨n⟩      (Default: 32)
-fmax-relevant-binds=⟨n⟩           (Default: 6)
-fmax-uncovered-patterns=⟨n⟩       (Default: 4)
-fmax-simplifier-iterations=⟨n⟩    (Default: 4) 
-fmax-worker-args=⟨n⟩              (Default: 10)
-fsimplifier-phases=⟨n⟩            (Default: 2)
-fsimpl-tick-factor=⟨n⟩            (Default: 100)
-fspec-constr-count=⟨n⟩            (Default: 3)
-fspec-constr-threshold=⟨n⟩        (Default: 2000)
-fstrictness-before=⟨n⟩            -- no default value
-funfolding-creation-threshold=⟨n⟩ (Default: 750)
-funfolding-dict-discount=⟨n⟩      (Default: 30)
-funfolding-fun-discount=⟨n⟩       (Default: 60)
-funfolding-keeness-factor=⟨n⟩     (Default: 1.5)
-funfolding-use-threshold=⟨n⟩      (Default: 60)
```

And ~40 more boolean flags. Maybe default set of values for these flags is not optimal. Because most of them are some compiler heuristics, I guess. And there might not be strong argument why these exact numbers were chosen.

**Comment by mrkgnao** [comment]
You might want to see this by Don Stewart if you haven't:

https://donsbot.wordpress.com/2009/03/09/evolving-faster-haskell-programs/

**Comment by chshersh** [comment]
@mrkgnao Thanks! This is exactly the idea I had in mind! But I wasn't aware it's already implemented for Haskell. Probably outdated, but still.
