### ISSUE TITLE
Idea: Make Hackage fully CDN-aware

### ISSUE THREAD

**Issue by gbaz** [haskell-org/summer-of-haskell#14]
We have speed and bandwidth issues with the hackage  package repository due to needing to disable the CDN for too many pages. This is because when the CDN is on, it caches things people don't expect -- in particular, things that can be updated due to user action.

There are utility functions in the hackage codebase to teach each page to send proper cache-control headers to keep the CDN from serving stale content. However, they aren't used carefully and uniformly.

Additionally, the CDN interferes with our ability to collect download statistics. 

This would be a two phase project -- first annotate hackage pages carefully to ensure that the CDN doesn't cause confusion with regards to updates to pages. Second, design a solution to both allow caching of package downloads and _also_ collect granular statistics. One possibility is to serve downloads via redirects, with the redirect always being hit, and the redirected-to tgz file being cached.

**Comment by jaspervdj** [comment]
This sounds good.  I can turn it into a proposal.  Would you be willing to mentor this, or do you have someone in mind?

**Comment by gbaz** [comment]
We can handle it between myself and @hvr with @dcoutts consulting.

(speaking of which -- any suggestions from you two for other hackage projects? finally getting revdeps in shape? maybe combined with richer search filtering and...?)

**Comment by jaspervdj** [comment]
I'm closing this issue to keep things tidy but please suggest another hackage project.  :-)
