### ISSUE TITLE
Improvements in UI and Logo 

### ISSUE THREAD

**Issue by ChiragDogra** [haskell-org/summer-of-haskell#141]
## 1. The highlight of navbar items
Hightlight while hovering on the nav-items can be made more appealing

## 2. Logo for navigation
Logo of the website can be used to navigate to the homepage.

**Comment by ChiragDogra** [comment]
I was trying to fix it, But I am not able to run the project on my localhost.

**Comment by leesha19** [comment]
@jaspervdj hey can i work on this issue....
i saw this project on gsoc so i wanna know are you going to participate in gsoc 2022 ..and i have knowledge of html css and js how and where i can help

**Comment by jaspervdj** [comment]
Hi, yes, we are open to contributions here, but keep in mind this is just a small repository that hosts the rather simple website for GSoC -- contributions to actual Haskell libraries and applications would be vastly more valuable, for example, [HLS has a number of issued tagged "beginner"](https://github.com/haskell/haskell-language-server/labels/beginner%20friendly).  We are currently working getting a more comprehensive list of ideas on the summer.haskell.org website as well.

**Comment by jaspervdj** [comment]
Cleaning up for 2023, if you receive this notification and have ideas from this year, please submit them!
