### ISSUE TITLE
Modularizing GHC

### ISSUE THREAD

**Issue by Ericson2314** [haskell-org/summer-of-haskell#158]
*In #143 @mmhat initially took an interest in "trees that grow", but given that that project already has a recent new contributor (@alt-romes), opted to do work on GHC modularization. This, however, hasn't been proposed as an HF project at this time, so #143 isn't actually a very good place to continue discussing it. Finally, as we are now well underway working to bring more awareness to this project and have a solid GSOC application for the April 19th, due date, so a dedicated issue is warranted anyways.*

GHC is currently quite entangled and anti-modular. We will soon link *immensely* more background info here, but for now see https://gitlab.haskell.org/ghc/ghc/-/issues/17957 which has a decent roadmap in the form of carefully ordered TODO items.

mentee: @mmhat 

mentors: @ericson2314, @hsyl20, and @doyougnu (but probably not all of us officially)

**Comment by jaspervdj** [comment]
This sounds awesome.

@Ericson2314 can you send me an email including the email addresses of the prospective mentors, so I can invite them to the GSoC dashboard?

@mmhat Let me know if you need anything, but be sure to register on the GSoC dashboard and submit this there :-)

**Comment by Ericson2314** [comment]
> This sounds awesome.

Glad to hear it!

Email is sent.

**Comment by mmhat** [comment]
> Let me know if you need anything, but be sure to register on the GSoC dashboard and submit this there :-)

@jaspervdj Thank you; I will drop you a note if that is the case. I am already registered and I will submit the proposal there by the time it's done.

**Comment by mmhat** [comment]
The project proposal got accepted :tada: 
https://summerofcode.withgoogle.com/programs/2022/projects/WWgHBTde

**Comment by jaspervdj** [comment]
Cleaning up for 2023, if you receive this notification and have ideas from this year, please submit them!
