### ISSUE TITLE
Meta-discussion about 2018 setup

### ISSUE THREAD

**Issue by saurabhnanda** [haskell-org/summer-of-haskell#19]
- Is it the [Reddit thread](https://www.reddit.com/r/haskell/comments/7m1mum/summer_of_haskell_call_for_ideas_for_2018/)?
- Is it this repo?
- Or, is it some mailing list?

Also, what happened to the other ideas at https://summer.haskell.org/ideas.html ?

**Comment by wisn** [comment]
Don't use Reddit please since in several countries (like Indonesia) blocked by the government. Can we use another platform, @jaspervdj? Several organizations use [Gitter](https://gitter.im/), [Slack](https://slack.com/), or [Zulip](https://zulipchat.com/) for their GSoC discussion.

**Comment by saurabhnanda** [comment]
Actually, even this Github repo is fine, because it allows one to tag other people/orgs on Github.

**Comment by gbaz** [comment]
Ideas should be submitted to the repo as PRs or tickets. There is a #haskell-gsoc channel we have used on freenode in the past. The old ideas that were deleted were the ones that were successfully completed last year, so should not serve as the basis for new proposals.

**Comment by wisn** [comment]
Yes, it is fine to use GitHub. Mailing list is a bit...

**Comment by saurabhnanda** [comment]
> The old ideas that were deleted were the ones that were successfully completed last year, so should not serve as the basis for new proposals.

Is the old ideas page archived somewhere? Ideally everything should be archived under /2017 (or /2016).

As per [the timeline](https://summerofcode.withgoogle.com/how-it-works/#timeline) - applications for organizations will be open from 4-23 Jan. We have only two ideas till now?

**Comment by wisn** [comment]
I've ask several projects.

- https://github.com/haskell-servant/servant/issues/880
- https://github.com/bos/aeson/issues/616
- https://github.com/hspec/hspec/issues/339

**Comment by saurabhnanda** [comment]
I've asked one - https://github.com/lpsmith/postgresql-simple/issues/242 and also HIE (via IRC).

**Comment by jaspervdj** [comment]
I also prefer using GitHub since it is easy to set up (unlike a mailing list), most people have an account already, and it's persistent (unlike Slack/IRC).

**Comment by saurabhnanda** [comment]
Formally pinged HIE at https://github.com/haskell/haskell-ide-engine/issues/434

**Comment by saurabhnanda** [comment]
Re-confirming we have only 2 ideas submitted formally? Btw, as per the [timeline](https://summerofcode.withgoogle.com/how-it-works/#timeline) applications for organizations open today.

**Comment by gbaz** [comment]
We have some others sitting around in PRs. I don't think we need them all in until the deadline, but this is a good reminder that we should round some further ones up...

**Comment by jaspervdj** [comment]
I'm hoping to have 6-8 ideas by the time we submit.  I'm a bit busy this week but will have time over the weekend to flesh things out.

**Comment by alanz** [comment]
@saurabhnanda See https://github.com/haskell-org/summer-of-haskell/pull/36 for HIE

**Comment by wisn** [comment]
Congratulation! Haskell accepted as a mentor organization in GSoC 2018! See [here](https://summerofcode.withgoogle.com/organizations/5706672807346176/). Thank you for your hard work @jaspervdj et al.
