### ISSUE TITLE
Use Materialize CSS Framework

### ISSUE THREAD

**Issue by wisn** [haskell-org/summer-of-haskell#2]
I do love to use Material design for Summer of Haskell website. May I?

**Comment by wisn** [comment]
Currently, it's looks like this.

![screenshot from 2017-04-01 17-54-15](https://cloud.githubusercontent.com/assets/8147926/24578127/473c91be-1704-11e7-84f1-4e5cd4fab8a5.png)

This is the main *navbar* and the home page header.

**Comment by jaspervdj** [comment]
Thanks for the  effort, but I'd prefer to keep the site very simple if possible, so I think it's better not to use a framework right now.
