### ISSUE TITLE
Find mentor(s) for GHCI space leak idea

### ISSUE THREAD

**Issue by gwils** [haskell-org/summer-of-haskell#29]
The GHCI space leak idea at content/ideas/ghci-space-leak.md does not have any mentors listed.
We should find a mentor for the idea or delete it.

**Comment by gbaz** [comment]
It is better to have mentors but not strictly necessary imho?

**Comment by saurabhnanda** [comment]
I have broadcasted a message on the three related issues. Let's see if anyone is interested in mentoring students.

**Comment by mpickering** [comment]
I don't think this project is very good for HSoC. The scope is too narrow and it is a difficult problem to get to grips with and make progress. I feel like projects which allow easily measurable incremental improvements are a better fit.

**Comment by saurabhnanda** [comment]
**I believe that this project has a very measurable outcome -- with a big positive impact to the community.**

As to whether it is appropriate for a student in GSoC/HSoC, I will leave it to the GHC team to decide. Please feel free to remove this idea if GHC devs decide that it is not appropriate for a student (with appropriate mentoring).

**Comment by ndmitchell** [comment]
I'm very keen for this to be fixed, but like @mpickering, I don't think it's a great fit for HSoC. I think it likely requires Simon Marlow level knowledge, followed by a 2 character change. It is measurable and has a positive impact, but I suspect it's just too tough and too hard going.

**Comment by jaspervdj** [comment]
Okay, @ndmitchell and @mpickering know what they are talking about.

**Comment by saurabhnanda** [comment]
Btw, just wondering if https://github.com/haskell-org/summer-of-haskell/blob/master/content/ideas/ghc-type-system.md is also a good idea for HSoC for similar reasons?

**Comment by mpickering** [comment]
I wondered the same but I think it would be ok given the right student as Richard already knows how to implement the idea. As such, he can give precise guidance to guide the right person. It will undoubtedly be difficult but I'm sure the selection committee will recognise that only a very qualified and motivated candidate could complete the project.

This is different as no one knows how to solve it or how to make any progress at all in the matter.

**Comment by saurabhnanda** [comment]
> This is different as no one knows how to solve it or how to make any progress at all in the matter.

I was afraid of hearing this 😞 

Is there any other way of attracting more eyeballs to this issue so that it has a higher chance of getting fixed?

**Comment by ndmitchell** [comment]
Buy Simon Marlow a beer.
