### ISSUE TITLE
Adding knowledge prerequisites field to each project (suggestion)

### ISSUE THREAD

**Issue by pranjaltale16** [haskell-org/summer-of-haskell#30]
How about adding the knowledge prerequisite field to each project?
Many projects require some extra knowledge associated with that project.
We can add an extra field to each project, like [this](http://clojure-gsoc.org//project-ideas/).

**Comment by jaspervdj** [comment]
I don't think it's necessary.  We want our idea list to look like prose and not like a bug tracker / spreadsheet with a bunch of fields: <https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list>

As for the students, I think figuring out what they need in terms of knowledge is part of writing a good proposal.

**Comment by pranjaltale16** [comment]
True!
Sound good, I think we should close this.
