### ISSUE TITLE
Project Idea: Representing Inaccessible Patterns using ImpossibleCases

### ISSUE THREAD

**Issue by Abhiroop** [haskell-org/summer-of-haskell#32]
There has already been a discussion and a follow-up proposal for this idea here: https://ghc.haskell.org/trac/ghc/ticket/10756#comment:4

The basic gist of the idea is the ability to represent impossible cases in pattern matching like this (from Idris):

```haskell
f : Num a => (n : Nat) -> Vect n a -> Nat
f Z [] = 0
f Z (_::_) impossible

f (S n) (x::xs) = x + f n xs
f (S _) [] impossible -- demarcating the impossible case
```
This feature is already present in languages like Idris. I am not sure about the difficulty level of the extension and if it is too trivial to qualify as a summer of Haskell project. Also, the relative utility and relevance of this is not very clear to me. Kindly feel free to consider or remove this idea.

**Comment by jaspervdj** [comment]
@Abhiroop I'm cleaning up issues in preparation for the 2019 GSoC, but feel free to resubmit this idea!
