### ISSUE TITLE
Merged ideas aren't showing up on the website

### ISSUE THREAD

**Issue by wz1000** [haskell-org/summer-of-haskell#37]
It seems many ideas that have be merged aren't showing up on the [Ideas page of the Summer of Haskell website](https://summer.haskell.org/ideas.html)

This includes https://github.com/haskell-org/summer-of-haskell/pull/15, https://github.com/haskell-org/summer-of-haskell/pull/33 and https://github.com/haskell-org/summer-of-haskell/pull/34

All I can see on the page now is:
- Implement quantified contexts (or other type system goodies)
- Finish the package candidate workflow for Hackage
- Make Hackage CDN-aware
- Add a CommonMark parser to Pandoc

**Comment by jaspervdj** [comment]
Thanks for the heads up!  I hadn't deployed in a while because I was merging PRs from my phone (traveling).  Should be fixed now.
