### ISSUE TITLE
Project proposal: implement Eisenberg's Pico in GHC as a new core language

### ISSUE THREAD

**Issue by mrkgnao** [haskell-org/summer-of-haskell#47]
I'm first doing a clean implementation of Pico [here](https://github.com/mrkgnao/pico). @goldfirere has expressed interest in this proposal in an email.

Mentor possibilities: @goldfirere

**Comment by jaspervdj** [comment]
Is this an idea for students to work on, our your personal student proposal?

Student proposals are not due until March 12 and they are not submitted through GitHub.

**Comment by mrkgnao** [comment]
I see, sorry for the noise. This was indeed a proposal for myself.
