### ISSUE TITLE
idea sketch: improve option parsing and display for cabal

### ISSUE THREAD

**Issue by gbaz** [haskell-org/summer-of-haskell#78]
This is a big refactor and I can't write exactly how it would go, but I think the new- commands don't really differentiate between local and global options for command specific help, not to mention which in general we probably could refactor the whole setup to use say extensible records or at least some sort of context monad instead of the extremely painful process we have now. @hvr @phadej @23Skidoo @typedrat may all have ideas?

**Comment by hvr** [comment]
(speaking of refactors, we have https://github.com/haskell/cabal/wiki/Potential-Refactors which @fgaz started; but we also have this big "Cabal Monad" refactoring on the roadmap... which should probably happen or at least be taken into account for any other major refactoring such as CLI refactoring...)

**Comment by jaspervdj** [comment]
Closing this to clean up for GSoC 2020.
