### ISSUE TITLE
Project Idea: Improve GHC cold compilation times

### ISSUE THREAD

**Issue by typesanitizer** [haskell-org/summer-of-haskell#79]
I've done some very preliminary investigation [here](https://www.reddit.com/r/haskell/comments/a1u9qj/monthly_hask_anything_december_2018/ecp262e).

---

GHC is an amazing compiler, with lots of optimizations to make your code run well. Unfortunately, users pay the price for this in terms of compilation time. Some initial investigation shows that when cold compiling the `containers` package, 50% of the compiler's time is spent in the simplifier, 27% doing garbage collection, and 16% in the code generator. There are several possible enhancements here -

* Raw performance improvements - Can allocations be reduced in the simplifier, putting less work on the GC? Can the default GC parameters for GHC's binary be tweaked to reduce the time spent doing GC? Can the simplification for case expressions (which takes 14% of compile time for `containers`) be made faster?

* Better profiling information - Presently, one can profile GHC using a profiling build and passing options to the RTS. However, this means the profiles are available for a whole package basis, not on a per-module basis. While this is good enough when isolating performance problems, this cannot be used to identify hot modules when compiling large packages. This also makes it harder to report performance problems as a compiler user.

Improving compiler performance will have a drastic productivity benefit on users of large codebases due to faster feedback loops both locally and in continuous integration.

---

The three key problems (as I see it) are

1. Mentorship - Do any of the GHC developers have enough bandwidth available in the summer to be able to mentor a student?

2. Too broad - As it stands, the proposal feels quite broad and there's lots of ways to go about things. Which packages should be investigated first? I feel highly used packages such as `containers`, `text` and `vector` serve as good examples. If time permits, it would be useful to investigate other packages such as `lens` (it has high downloads and more type-level programming). There's also room for working on better reporting (e.g. timings on a per module basis or per top level definition basis).

3. Possibly inaccurate - What I've written here is based on my initial investigation (mostly documented in the linked comment at the beginning) and reading through the profiling related bits on GHC Trac. Maybe I've missed something important here and some points and not quite right. Would having per-module profiling information be useful? Per top-level-definition? Would adding support for something like to GHC's existing architecture be too painful?

If some GHC developers could chime in with their thoughts on the matter, that'd be awesome. CC @bgamari, @simonpj, @RyanGIScott

**Comment by osa1** [comment]
CCing @tdammers who probably did the most work on this area (compile-time performance).

**Comment by mpickering** [comment]
I think there is scope for a focused project about profiling but the idea needs to be refined for it to have a reasonable scope.

**Comment by simonpj** [comment]
I'd be very happy to see people working on this.   Reducing compile times is THE top ask in our GHC-user surveys.

The GHC team has tended to focus on "outliers"; that is, programs where GHC takes egregiously long to compiles something, usually exposing some dark corner.  But this seldom improves average-case behaviour.

I think it'd be great to work on improving **average-case performance** of GHC itself.  I doubt there is any very-low-hanging fruit, but there must be **some** that is not hard to pluck.

You might find that better profiling tools are needed.   But it's be ambitious to (a) identify the need (b) work out how to implement that new form of profiling (c) do the implementation (d) use it to improve GHC, all in the scope of a GSOC project.

**Comment by saurabhnanda** [comment]
Just a wild thought -- fundraising for this goal [1] and moving it outside GSoC if it needs more commitment and people with more experience working on this problem.

[1] Goal will probably need to be defined very clearly for fundraising to be successful.

**Comment by jaspervdj** [comment]
@saurabhnanda Even if we raise funds for this and do work outside of GSoC, I still think it makes sense to have this within GSoC as well -- it's a good opportunity for a student.

I agree that the idea is a bit too broad as it stands.  Perhaps we could focus this on only implementing improved profiling tools that work with a few popular packages (`containers`, `lens`, `text`, `vector`...).

**Comment by MaxGabriel** [comment]
Maybe a smaller version of this project is some way to benchmark compile times and just graph that over time? So that performance regressions could potentially be identified

**Comment by gbaz** [comment]
we had the ghc performance dashboard, but it seems to have gone broken? https://perf.haskell.org/ghc/

**Comment by typesanitizer** [comment]
I've opened a PR with an updated proposal which is more measured - it is only about profiling and optimization is out of scope. It also focuses less on the benefits and more on the "what needs to be done in this project". Let's continue the discussion there so you can easily comment on individual lines if needed.
