### ISSUE TITLE
idea sketch : language server for dhall

### ISSUE THREAD

**Issue by alanz** [haskell-org/summer-of-haskell#90]
From http://www.haskellforall.com/2019/01/dhall-year-in-review-2018-2019.html

> Editor support
>
> Another thing Dhall is missing compared to YAML is widespread editor support. This is why another one of my goals for this year is to create a Dhall language server so that any editor that supports the language server protocol (basically all of them) would get Dhall support for free.

So, use `haskell-lsp` to construct a LSP server for dhall.  Similar to the ones for

- https://github.com/haskell/haskell-ide-engine
- https://github.com/elm-tooling/elm-language-server
- https://github.com/domenkozar/hnix-lsp

Which are all based on that library.

cc @Gabriel439

**Comment by jaspervdj** [comment]
This sounds great!  @Gabriel439 would you be able to put a short proposal together?

**Comment by Gabriella439** [comment]
Sorry, looks like I lost track of this and missed the deadline for this :\

I'll try again for next year's Google Summer of Code

**Comment by gwils** [comment]
You're still welcome to add ideas to the list. Our application is already in but that doesn't prevent us from adding project ideas.

**Comment by gbaz** [comment]
Right -- the ideas are useful as long as there are students considering writing proposals!

**Comment by Gabriella439** [comment]
Where would I or the student submit the project proposal?

**Comment by gwils** [comment]
Submit an "idea" as a pull request on this repo (eg. https://github.com/haskell-org/summer-of-haskell/pull/102)

A bit over a month from now, interested student(s) should write up proposal(s) based on the idea, and submit them through the GSOC system.
