### ISSUE TITLE
Offer the "Binary backend for Postgresql/Persistent" idea again in 2019

### ISSUE THREAD

**Issue by sjakobi** [haskell-org/summer-of-haskell#96]
I'm referring to [this idea](https://github.com/haskell-org/summer-of-haskell/commit/a7af171c93f394e4e2c198294d7af3e3518c2627#diff-f13a76b459ce796f5f6d4a09746591e0) from 2018.

I considered applying for it in 2018 but preferred doing something related to GHC in the end.

@erikd, @nikita-volkov, @MaxGabriel, would you be available as mentors again?

**Comment by MaxGabriel** [comment]
Probably not—we have two interns at my company this summer so I should probably focus on them. Maybe open an issue on the persistent repo to ask about this?

**Comment by erikd** [comment]
I would be willing but would like to have at least one other mentor, preferably @nikita-volkov (as the author/maintainer of Hasql) is also involved.

**Comment by nikita-volkov** [comment]
I can be available in the mode of answering questions, but I must mention that I'm gonna be of limited involvement, because I'll be highly preoccupied at work.

**Comment by sjakobi** [comment]
Thanks for letting me know about your availability as mentors this summer!

Sadly, there hasn't been any reaction to [my call for mentors from the `persistent` community](https://github.com/yesodweb/persistent/issues/851) so far.

@erikd Would you still like to go forward with the proposal idea or does it look to risky now?

**Comment by erikd** [comment]
It looks pretty risky to me at the moment.

**Comment by jaspervdj** [comment]
Closing this to clean up for GSoC 2020.
